#.s   : Asembler source file
#.cpp : C++ source file
#.hpp : C++ header file include source
.SUFFIXES: .s .cpp .hpp

CC = gcc-4.7.3
CXX = g++-4.7.3

CFLAGS = 
CXXFLAGS += -std=c++11

INCLUDEDIR = 
LIBRRAYDIR = 

.c.o:
	$(CC) ${CFLAGS} -c $< ${addprefix -I, INCLUDEDIR} ${addprefix -L, LIBRARYDIR}
.cpp.o:
	$(CXX) ${CXXFLAGS} -c $< ${addprefix -I, INCLUDEDIR} ${addprefix -L, LIBRARYDIR}
.s.o:
	$(CC) -c $<


