MATH_UTIL = ${HOME}/Projects/MathUtil
COMPLEX = ${MATH_UTIL}/Complex
LIBRARY = ${MATH_UTIL}/Library
UTILITY = ${MATH_UTIL}/Utility

.c.o:
	$(CC) ${CFLAGS} -c $< -I{MATH_UTIL}
.cpp.o:
	$(CXX) ${CXXFLAGS} -c $< -I{MATH_UTIL}
.s.o:
	$(CC) -c $<
